// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD18vkBYmmNe5LgxCsPR7GxwohQubRgFFE',
    appId: '1:902874816476:web:c5b5785fb65bab58be37f8',
    messagingSenderId: '902874816476',
    projectId: 'rypstick-new',
    authDomain: 'rypstick-new.firebaseapp.com',
    storageBucket: 'rypstick-new.firebasestorage.app',
    measurementId: 'G-2X9LKJ44QEG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9GNC7nkcHFB1roO-r-_9YI1Hi0ADCSMo',
    appId: '1:902874816476:ios:41455a7e46cea8751df919',
    messagingSenderId: '902874816476',
    projectId: 'rypstick-new',
    storageBucket: 'rypstick-new.firebasestorage.app',
    iosBundleId: 'com.rypstick.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ0XjoO-uTr_PcNDeHJ0slRAhocHqPFJY',
    appId: '1:902874816476:ios:41455a7e46cea8751df919',
    messagingSenderId: '902874816476',
    projectId: 'rypstick-new',
    storageBucket: 'rypstick-new.firebasestorage.app',
    iosBundleId: 'com.rypstick.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD18vkBYmmNe5LgxCsPR7GxwohQubRgFFE',
    appId: '1:696081141609:web:ff0d88309ca8cc5dbe37f8',
    messagingSenderId: '696081141609',
    projectId: 'blueconnect-2187e',
    authDomain: 'blueconnect-2187e.firebaseapp.com',
    storageBucket: 'blueconnect-2187e.firebasestorage.app',
    measurementId: 'G-V3CX7ZXRDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9GNC7nkcHFB1roO-r-_9YI1Hi0ADCSMo',
    appId: '1:902874816476:android:41455a7e46cea8751df919',
    messagingSenderId: '902874816476',
    projectId: 'rypstick-new',
    storageBucket: 'rypstick-new.firebasestorage.app',
  );
}
